### PR TITLE
Removing github action warnings.

### PR DESCRIPTION
**Pull request by BigUstad**
* Fixing missing closing/opening XML tags.
* Removing instances of Parameter (IRestResponse, RestRequest), if possible
* In Functional Tests removing async for some calls.
* Marking some functions as obsolete if missing, changing accordingly.
* Removing unused, initialized variable.
* Removing unnecessary 'using' statements.

### CODE REVIEW

**Review by ebozduman — CHANGES_REQUESTED** [review]
@BigUstad 

There are still `GitHub Actions` warnings in `Minio/ApiEndpoints/BucketOperations.cs` file:
Example:
```
Check warning on line 90 in Minio/ApiEndpoints/BucketOperations.cs

GitHub Actions
/ build (Release)
Minio/ApiEndpoints/BucketOperations.cs#L90
The method 'MakeBucketAsync' do not need to use async/await.
```
See `Minio/ApiEndpoints/BucketOperations.cs` file under `Files Changed` of this PR.

I also see total 67 warnings during build. I am sure we are not going to address them all, but you may want to check them out too.

**Comment by BigUstad** [comment]
> @BigUstad
> 
> There are still `GitHub Actions` warnings in `Minio/ApiEndpoints/BucketOperations.cs` file:
> Example:
> 
> ```
> Check warning on line 90 in Minio/ApiEndpoints/BucketOperations.cs
> 
> GitHub Actions
> / build (Release)
> Minio/ApiEndpoints/BucketOperations.cs#L90
> The method 'MakeBucketAsync' do not need to use async/await.
> ```
> 
> See `Minio/ApiEndpoints/BucketOperations.cs` file under `Files Changed` of this PR.
> 
> I also see total 67 warnings during `dotnet build`. This list also includes the above `GitHub Actions` warnings.
> They look like all belong to your to be fixed list in this PR's description/
> Here is the short list of those warnings.
> 
> ```
> (32) The method '<method-name>' do not need to use async/await
> (28) MinioClient.<object-builder-name(...)> is obsolete
> (4) CopyToAsync should be used instead of stream.CopyTo
> (2) Initialize is a fire & forget async void method
> (1) This async method lacks 'await' operators and will run synchronously.
> ```

The "do not need to use async/await" is definitely wrong as `async/await` combination is definitely needed. So a workaround is needed for this warning. I'm looking into it.
I'll also look into the obsolete warnings

**Comment by BigUstad** [comment]
@ebozduman Please try with the latest patchset.

**Review by ebozduman — APPROVED** [review]
Priyank said he'll address the last 2 warnings about `stream.CopyTo`.
So, LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
