### PR TITLE
Feat replace dynamic with class

### PR DESCRIPTION
**Pull request by martijn00**
Updated version of https://github.com/minio/minio-dotnet/pull/795

@ebozduman can you run this?

### CODE REVIEW

**Review by ebozduman — APPROVED** [review]
LGTM

**Comment by martijn00** [comment]
@ebozduman Ive done a rebase to fix the conflict. Van you run again?

**Comment by martijn00** [comment]
@ebozduman now it should be correct. Can you run again?

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
