### PR TITLE
Fixes adding additional QueryParameters to http request

### PR DESCRIPTION
**Pull request by tvdias**
It looks like there's an issue on HttpRequestMessageBuilder.Request getter. I've written a test and could check it doesn't do what I expected it to do.

I've changed it to get Uri's query parameters and always append `QueryParameters`.

### CODE REVIEW

**Review by martijn00 — APPROVED** [review]

**Comment by tvdias** [comment]
hey @martijn00 , I've written an additional test making clearer the expected behavior.

**Review by martijn00 — APPROVED** [review]

**Comment by martijn00** [comment]
@ebozduman can you run this and review?

**Comment by martijn00** [comment]
@tvdias can you run format on this branch?

**Comment by tvdias** [comment]
> @tvdias can you run format on this branch?

I run the tool to format both files and updated the PR, but it didn't run the pipeline again, so I can't confirm this is now as expected.

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
