### PR TITLE
Fix objects with spaces in name not returned correctly fixes #1100

### LINKED ISSUE #1100: Files uploaded with spaces in the name are returned with pluses in ListObjectsEnumAsync
similar to issue #342 the new method ListObjectsEnumAsync suffers from the problem where the item's Key contains a plus where the space was, so if the result are used for subsequent requests the item isn't found.

A `Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=The specified key does not exist.` exception is raised

### PR DESCRIPTION
**Pull request by heedfull**
The Uri.UnescapeDataString method has been replaced with the HttpUtility.UrlDecode method in the BucketOperations.cs file to correctly decode the item Key. Additionally, the ListObjects_Test7 function has been added to the functional tests to test whether ListObjects lists all objects matching a prefix with a space in a non-recursive manner.

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
We need to add support for encoding-type=url for List() and keep the URL escape.

**Comment by heedfull** [comment]
I'm not really sure what you mean. The new functional test I added fails without the change submitted. This is the same fix that was used for #343 

There are no new failing tests because of these changes

**Comment by heedfull** [comment]
> We need to add support for encoding-type=url for List() and keep the URL escape.

that's not what I was hoping to achieve with this PR. I want to add support for objects with spaces in their name. Maybe if you can give more details in separate issue then I can take a look.

**Comment by harshavardhana** [comment]
> > We need to add support for encoding-type=url for List() and keep the URL escape.
> 
> that's not what I was hoping to achieve with this PR. I want to add support for objects with spaces in their name. Maybe if you can give more details in separate issue then I can take a look.

Try uploading an object with + in its name this PR will break.

**Comment by heedfull** [comment]
I've added a test for a prefix with a plus character in it. It passes before and after the change.

**Comment by harshavardhana** [comment]
The reason this works is its already added https://github.com/minio/minio-dotnet/blob/5226fa47663110f05566d24a24cd3f85216d4056/Minio/DataModel/Args/GetObjectListArgs.cs#L96

**Review by harshavardhana — DISMISSED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by heedfull** [comment]
Anything I can do to help get this PR merged?

**Comment by ebozduman** [comment]
Sorry @heedfull 
I did not notice the progress in this PR.
Running the build tests now.
As soon ass the build test is complete, I'll merge it.

**Comment by heedfull** [comment]
no worries, thanks for merging.

Any plans to ship a new version of nuget package?

**Comment by ebozduman** [comment]
@heedfull 

> Any plans to ship a new version of nuget package?


Yes. It is in the plan.
There is a regression problem we are working on.
A new nuget package will be generated as soon as the regression issue is resolved.

**Comment by heedfull** [comment]
do you have a failing test for the regression? anything I can help with?

**Comment by ebozduman** [comment]
@heedfull 

Thank you.
I filed issue #1105 for it.
The culprit is a commit in PR#1057. I have a fix and will create the PR in a bit.

**Pull request merged**
