### PR TITLE
Rework parallel util method

### PR DESCRIPTION
**Pull request by martijn00**
@ebozduman what about this one

### CODE REVIEW

**Comment by ebozduman** [comment]
It looks like the CRLF issue is still lingering around.

regitlint job fails with bunch of similar CRLF messages ...
```
error:warning: in the working copy of 'SimpleTest/Program.cs', CRLF will be replaced by LF the next time Git touches it
```

I thought we've fixed it for good with PR#802, provided that our setups are not going to introduce it again.

**Comment by martijn00** [comment]
Weird, I did not touch any files.

**Comment by martijn00** [comment]
@ebozduman Can you run this one?

**Comment by martijn00** [comment]
@ebozduman this should be ready now. Can you run?

**Review by ebozduman — APPROVED** [review]
LGTM

**Comment by martijn00** [comment]
@ebozduman not sure why the functional tests fail, it runs locally for me. Can you just run it again to see if it helps?

**Pull request merged**
