### PR TITLE
Mint - Avoid invalid JSON output

### PR DESCRIPTION
**Pull request by iternity-dotcom**
## Description
The console outputs have been removed and the exception handling for versioning and locking has been extended. 

## Motivation and Context
Testing with Mint Suite generates a log.json file. We want to process the file, but MinIO .NET generates invalid JSON in case of errors.
 
## How to test this PR?
Runing the tests against a `minio server data{1...4}` should now return a valid JSON without error stacktraces.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by iternity-dotcom** [comment]
@andrebruch fyi

**Review by poornas — APPROVED** [review]
LGTM

**Comment by poornas** [comment]
@iternity-dotcom , please fix the build failures

**Comment by ebozduman** [comment]
@iternity-dotcom,

Please fix the build check failure(s) and then build and verify your PR by running the Mint tests.

**Comment by harshavardhana** [comment]
Please resubmit the PR if this is still a problem - the project has been re-implemented.

**Pull request closed without merging**
