### PR TITLE
Warnings

### PR DESCRIPTION
**Pull request by martijn00**
@ebozduman another round of warnings.

### CODE REVIEW

**Comment by martijn00** [comment]
@ebozduman can you run again?

**Comment by martijn00** [comment]
@ebozduman trying to track down the test issues I find it sometimes difficult to see where they come from now they run in parallel. Do you have any suggestions?

I tried this:

```c#
        await Utils.RunInParallel(functionalTestTasks, async (task, _) => {
            try
            {
                await task.ConfigureAwait(false);
            }
            catch (Exception)
            {
                throw task.Exception;
            }
        })
            .ConfigureAwait(false);
```

Which does help a bit to see the inner exception. What do you think?

**Comment by ebozduman** [comment]
@martijn00 

Great idea!
I'll also use it.

**Comment by martijn00** [comment]
@ebozduman can you run this one again?

**Comment by ebozduman** [comment]
> ...sometimes difficult to see where they come from now they run in parallel. Do you have any suggestions?

I forgot to answer your previous question.

I used the following cancellation token related change at the end of the `ExecuteTaskCoreAsync` function to see if the test stops because a cancellation was requested.

```
        catch (OperationCanceledException ex)
        {
            if (ex.CancellationToken.IsCancellationRequested )
            {
                Console.WriteLine($"\n\n\nYes, Cancellation Requested\n\n\n");
            }
            throw;
        }
        catch (Exception e)
        {
            responseResult?.Dispose();
            responseResult = new ResponseResult(request, e);
        }

        HandleIfErrorResponse(responseResult, errorHandlers, startTime);
        return responseResult;
    }
```

**Comment by ebozduman** [comment]
@martijn00 

I guess you need to run `dotnet regitlint`.
```
!!!! Process Aborted !!!!
The following files do not match .editorconfig:
 * Minio/Credentials/AssumeRoleProvider.cs
 * Minio/DataModel/Args/PutObjectPartArgs.cs
 * Minio/DataModel/Tags/Tagging.cs
 * Minio/ResponseResult.cs
Error: Process completed with exit code 1.
```

**Comment by martijn00** [comment]
@ebozduman done. can you run again?

**Comment by martijn00** [comment]
@ebozduman all green here! Can you merge?

**Comment by ebozduman** [comment]
currently reviewing.
As soon as I am done, I'll merge the PR

**Review by ebozduman — DISMISSED** [review]
LGTM

**Review by ebozduman — COMMENTED** [review]
LGTM

**Review by ebozduman — APPROVED** [review]

**Pull request merged**
