### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by martijn00**
@ebozduman

### CODE REVIEW

**Comment by ebozduman** [comment]
@martijn00 
I took the liberty to add a clean up code change in this PR, the unnecessary targets in our tests. 
These unnecessary targets were required to be installed in the container where the release script runs.

**Comment by martijn00** [comment]
@ebozduman fine with me! Any other areas of the code you feel cleanup is required?

**Comment by ebozduman** [comment]
I think we have more than enough to make a release.
I am currently testing the release process.
As soon as I am done, we'll make a new release.

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
