### PR TITLE
Fixes dotnet mint test and cleanup issues against Azure

### PR DESCRIPTION
**Pull request by ebozduman**
minio-dotnet functional tests are run under Mint and there were left over test objects and buckets after test runs.
This PR cleans those left over objects and buckets and also addresses some test issues existed in some of the functional tests.

### CODE REVIEW

**Review by poornas — APPROVED** [review]
LGTM

**Comment by BigUstad** [comment]
@ebozduman Please resolve conflicts

**Comment by ebozduman** [comment]
This last commit addressed the merge conflicts and is supposed to fix the build failure(s).
Also modified the incorrect test result status from `"FAIL"` to `"NA"` for tests failing due to `"NotImplemented"` error message.
Still some cleanup, and beautifying can be done, like deciding on deciding. I tried to see if it is going to be a quick change, but it looks like it is going to take couple of hours.

**Review by BigUstad — APPROVED** [review]
LGTM.

**Pull request merged**
