### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by martijn00** [comment]
@ebozduman can you run the CI?

**Comment by martijn00** [comment]
@ebozduman not sure why linux fails... can you try run that one again?

**Comment by ebozduman** [comment]
Yes, I see the same failure for the other PR (#731) and trying again

**Comment by martijn00** [comment]
@ebozduman it seems to work now!

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
