### PR TITLE
* Improve testability with IMinioClient interface

### PR DESCRIPTION
**Pull request by luizcarlosfaria**
* Improving testability with IMinioClient interface
* Adding all non deprecated operations to IMinioClient
* Removing factory (With*()) operations from interface keeping on MinioClient class.

### CODE REVIEW

**Comment by ebozduman** [comment]
@luizcarlosfaria 

Please run `dotnet regitlint` on your branch as there are lint issues in some of the modified files. 
After that, obviously you need to push your changes again.

**Review by ebozduman — COMMENTED** [review]
There are some more references to `MinioClient minio` which might also be replaced with the new interface:
1 in `README`
1 in `Minio/Credentials/IAMAWSProvider.cs`
3 in `Minio.Examples/Cases/ListenBucketNotifications.cs`, `../ListIncompleteUploads.cs`, `../ListObjects.cs`
and some more in `Minio.Frunctional.Tests/FunctionalTest.cs`

**Comment by harshavardhana** [comment]
@ebozduman let's take this PR and you can make those relevant changes?

**Comment by ebozduman** [comment]
Will do.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
