### PR TITLE
Fixed time zone lost when serializing and parsing dates

### LINKED ISSUE #810: RetentionUntilDate in SetObjectRetentionArgs serialized to wrong value
When RetentionUntilDate property in SetObjectRetentionArgs class serialized, it formatted to ISO 8601 string, but time zone offset get lost. 
```
public static string To8601String(DateTime dt)
{
    return dt.ToString("yyyy-MM-dd'T'HH:mm:ssZ", CultureInfo.InvariantCulture);
}
```
As result if date in local time zone, minio server received date in past or future depending on time zone.
I tried pass date in UTC, but get error, because passed value checked against local time (DateTime.Now) always

```
if (DateTime.Compare(RetentionUntilDate, DateTime.Now) <= 0)
            throw new InvalidOperationException("Retention until date set using " + nameof(WithRetentionUntilDate) +
                                                " needs to be in the future.");
```

### PR DESCRIPTION
**Pull request by basrach**
Fixes #810 and #808

### CODE REVIEW

**Comment by ante-maric** [comment]
I would suggest that the whole library should work only with UTC and that names of parameters and properties clearly state that by using UTC suffix which is common convention. That would greatly simplify things. Working with local time bites you sooner or later.

**Comment by martijn00** [comment]
@ebozduman this looks good to go to me

**Comment by martijn00** [comment]
@basrach Try to do a Rebase instead of merge to fix the code style.

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
