### PR TITLE
Pick latest nuget version of sdk for functional tests

### PR DESCRIPTION
**Pull request by poornas**
Version of Minio.Netcore used by functional tests needs to be bumped up to latest release version

### CODE REVIEW

**Comment by harshavardhana** [comment]
@poornas can we add `.travis.yml` for minio-dotnet as well to run functional tests for each commit?

**Comment by poornas** [comment]
will do.

**Comment by harshavardhana** [comment]
Looks like travis is failing @poornas

**Comment by poornas** [comment]
Travis fails with missing linux dependency GLIBCXX_3.4.21. Will update PR after I identify a fix.

Failed to load /home/travis/build/minio/minio-dotnet/Minio.Functional.Tests/bin/Debug/netcoreapp1.1/ubuntu.16.04-x64/libhostpolicy.so, error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/build/minio/minio-dotnet/Minio.Functional.Tests/bin/Debug/netcoreapp1.1/ubuntu.16.04-x64/libhostpolicy.so)

**Comment by harshavardhana** [comment]
You should open a Travis bug and ask them. Since this looks like a configuration issue on their end.

**Comment by poornas** [comment]
Raised an issue on travis CI https://github.com/travis-ci/travis-ci/issues/8267

**Comment by poornas** [comment]
@vadmeste, could you pls add your reviews?

**Comment by NitishT** [comment]
Any more reviews pending here, or we are waiting for https://github.com/travis-ci/travis-ci/issues/8267 to be resolved?

**Comment by poornas** [comment]
@nitisht, I think we should decouple travis from this and merge. We can add back travis once their configuration issue is fixed.

**Comment by poornas** [comment]
@harshavardhana, barring Travis build fail, can this be approved?

**Pull request merged**
