### PR TITLE
Make IAMAWSProviderExample work again

### PR DESCRIPTION
**Pull request by ddudda174**
fixes example code for #1036

### CODE REVIEW

**Comment by ebozduman** [comment]
@ddudda174 

Please run `dotnet regitlint` to fix formatting problem in  `.../Minio.Examples/Cases/IAMAWSProviderExample.cs`.

**Comment by ddudda174** [comment]
> @ddudda174
> 
> Please run `dotnet regitlint` to fix formatting problem in `.../Minio.Examples/Cases/IAMAWSProviderExample.cs`.

I did, but I get a lot of lint errors on the project, except the IAMAWSProviderExample.cs (I would guess it has something to do with the tabs/indent; I just removed them to see if it helps). Would you mind giving me a hint what could be wrong with the file formatting?

**Review by ebozduman — APPROVED** [review]
LGTM

**Comment by ebozduman** [comment]
@ddudda174 

I am not sure what lint errors you've seen but the format-check test is happy and passed.
So, no worries.
I'll approve the PR and merge it.

**Comment by ddudda174** [comment]
@ebozduman maybe it has something to do with Rider and it uses Rider's cleanup logic?

regitlint output looks like this:
```
PS C:\...\minio-dotnet> dotnet regitlint                  
No sln file specified. Searching for one...
Found .\Minio.sln. Using that.
JetBrains Cleanup Code 2023.3.3
Running on x64 OS in x64 architecture, .NET 8.0.3 under Microsoft Windows 10.0.22631
Version: 2023.3.3
JetBrains Cleanup Code 2023.3.3
Running on x64 OS in x64 architecture, .NET 8.0.3 under Microsoft Windows 10.0.22631
Using toolset version 17.0 from "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64"
Configuration: Debug, Platform: Any CPU
error: [MsBuild] C:\...\minio-dotnet\Minio\Credentials\WebIdentityProvider.cs (69,13)->(69,13) IDE0059: Unnötige Zuweisung eines Werts zu "credentials". (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Select\SelectEventType.cs (27,20)->(27,20) IDE0044: Schreibschutz für Feld festlegen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Response\ListObjectVersionResponse.cs (28,56)->(28,56) IDE0060: Nicht verwendeten Parameter "args" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Response\ListObjectsItemResponse.cs (28,54)->(28,54) IDE0060: Nicht verwendeten Parameter "args" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\RequestExtensions.cs (77,47)->(77,47) IDE0060: Nicht verwendeten Parameter "errorHandlers" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\ILM\RuleFilter.cs (45,13)->(45,13) IDE0059: Unnötige Zuweisung eines Werts zu "tag". (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059)
error: [MsBuild] C:\...\minio-dotnet\Minio\RequestExtensions.cs (77,47)->(77,47) IDE0060: Nicht verwendeten Parameter "errorHandlers" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\Credentials\WebIdentityProvider.cs (69,13)->(69,13) IDE0059: Unnötige Zuweisung eines Werts zu "credentials". (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Select\SelectEventType.cs (27,20)->(27,20) IDE0044: Schreibschutz für Feld festlegen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\ILM\RuleFilter.cs (45,13)->(45,13) IDE0059: Unnötige Zuweisung eines Werts zu "tag". (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Response\ListObjectsItemResponse.cs (28,54)->(28,54) IDE0060: Nicht verwendeten Parameter "args" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Response\ListObjectVersionResponse.cs (28,56)->(28,56) IDE0060: Nicht verwendeten Parameter "args" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\Credentials\WebIdentityProvider.cs (69,13)->(69,13) IDE0059: Unnötige Zuweisung eines Werts zu "credentials". (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Select\SelectEventType.cs (27,20)->(27,20) IDE0044: Schreibschutz für Feld festlegen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044)
error: [MsBuild] C:\...\minio-dotnet\Minio\RequestExtensions.cs (77,47)->(77,47) IDE0060: Nicht verwendeten Parameter "errorHandlers" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Response\ListObjectsItemResponse.cs (28,54)->(28,54) IDE0060: Nicht verwendeten Parameter "args" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\Response\ListObjectVersionResponse.cs (28,56)->(28,56) IDE0060: Nicht verwendeten Parameter "args" entfernen (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060)
error: [MsBuild] C:\...\minio-dotnet\Minio\DataModel\ILM\RuleFilter.cs (45,13)->(45,13) IDE0059: Unnötige Zuweisung eines Werts zu "tag". (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059)
```
I tried to fix some of those suggestions but getting more afterwards and cancelled that process. Also there might be later use of some parameters/variables that are currently not in use and get suggested to cleanup.

**Comment by ebozduman** [comment]
Not sure, but your commit helped.

**Pull request merged**
