### PR TITLE
#520 Fix the method - ToXML

### PR DESCRIPTION
**Pull request by lavkeshdwivedi**
There is no need to dispose the stream, it will and should be garbage collected

### CODE REVIEW

**Comment by lavkeshdwivedi** [comment]
@nitisht @poornas @krisis I'd appreciate a review and merge if all is well with the commit so that I can continue on further development. Thank you very much!

**Review by poornas — APPROVED** [review]
LGTM

**Review by krisis — APPROVED** [review]

**Comment by lavkeshdwivedi** [comment]
Please merge the changes @poornas @krisis @nitisht?

**Comment by harshavardhana** [comment]
Please rebase the PR with latest master @lavkeshdwivedi

**Comment by kannappanr** [comment]
This has been taken care of in the latest release

**Pull request closed without merging**
