### PR TITLE
Lifecycle expiration date, WithEndpoint, WithSSL issues cause functional tests to fail

### PR DESCRIPTION
**Pull request by ebozduman**
Fixes the functional tests, part of the CI and merge process, failures.

The following issues are addressed :
 - The life cycle expiration date is supposed to be replaced to the next day's midnight before the request is sent to the s3 server and the existing code was not doing it.
 - WithSSl(secure=false) is ignored
 - 3 versions of WithEndpoint() methods set endpoint either incorrectly and/or they were inconsistent
 - BucketExistsAsync method exception handling and responseResult interpretation were not correct.

### CODE REVIEW

**Comment by ebozduman** [comment]
@tvdias and others,
Sorry for the mix up.
Not sure how the other commits (@tvdias and others) made into my PR.
I am going to clean them up.

**Review by martijn00 — APPROVED** [review]

**Comment by ebozduman** [comment]
Yes... already working on it.

**Comment by ebozduman** [comment]
My fix works in my local setup and all 6 bucket lifecycle tests pass.
In the build testing though, all but `BucketLifecycleAsync_Test1.2` passes.
It looks like there is yet another problem still there and it is again another transient issue. 
I'll be looking into this new problem.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
PTAL CI failures @ebozduman

**Comment by ebozduman** [comment]
This PR also addresses issue #884

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
