### PR TITLE
Minioclient refactor with config

### PR DESCRIPTION
**Pull request by martijn00**
@ebozduman Can you review and let me know what you think of this approach to use a MinioConfig object for the properties? This would later enable better servicecollection actions, and also centralize config properties that can be accessed in the interface.

### CODE REVIEW

**Review by ebozduman — COMMENTED** [review]
@martijn00 

My comment (wrote it yesterday, but forgot to send)

Config idea sounds good to me. I see you've also added `DisposeHttpClient` in the config.
I've also noticed you've included PR #850 changes also here. Since PR #850 has been already merged, you can rebase this PR.
However, when I tried to rebase I saw conflicts you'd want to address.
I also could not build in your branch.

As you've already rebased and addressed the issues, I'll give it another try.

**Comment by martijn00** [comment]
@ebozduman It should be good to run now.

**Comment by ebozduman** [comment]
will re-review and run a couple of tests...

**Review by ebozduman — APPROVED** [review]
LGTM

**Pull request merged**
