### PR TITLE
Adds the new StatObjectAsync overload to IObjectOperations

### LINKED ISSUE #614: StatObjectAsync with StatObjectArgs was not added to IObjectOperations
StatObjectAsync with StatObjectArgs  was implemented in [ObjectOperations.cs](https://github.com/minio/minio-dotnet/blob/eb020da83e8be77affb0118ee7613dec9b1c52a9/Minio/ApiEndpoints/ObjectOperations.cs#L116), but was not added to [IObjectOperations.cs.](https://github.com/minio/minio-dotnet/blob/master/Minio/ApiEndpoints/IObjectOperations.cs)  Only the Obsolete StatObjectAsync is available in the Interface.

### PR DESCRIPTION
**Pull request by domn1995**
Closes #614

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
Please add a FunctionalTest.cs

**Comment by domn1995** [comment]
> Please add a FunctionalTest.cs

Sorry, not really seeing how to add a functional test for this since it just updates the interface with a method already implemented and tested by `MinioClient`. Can you point me in the right direction?

**Comment by harshavardhana** [comment]
> Sorry, not really seeing how to add a functional test for this since it just updates the interface with a method already implemented and tested by `MinioClient`. Can you point me in the right direction?

Look at FunctionalTest.cs

```csharp
    internal static async Task StatObject_Test1(MinioClient minio)
    {
        var startTime = DateTime.Now;
        var bucketName = GetRandomName(15);
        var objectName = GetRandomObjectName(10);
        var contentType = "gzip";

        var args = new Dictionary<string, string>
        {
            { "bucketName", bucketName },
            { "objectName", objectName },
            { "contentType", contentType },
            { "data", "1KB" },
            { "size", "1KB" }
        };

        try
        {
            await Setup_Test(minio, bucketName).ConfigureAwait(false);
            await PutObject_Tester(minio, bucketName, objectName, null, null, 0, null,
                rsg.GenerateStreamFromSeed(1 * KB)).ConfigureAwait(false);
            new MintLogger(nameof(StatObject_Test1), statObjectSignature, "Tests whether StatObject passes",
                TestStatus.PASS, DateTime.Now - startTime, args: args).Log();
        }
        catch (Exception ex)
        {
            new MintLogger(nameof(StatObject_Test1), statObjectSignature, "Tests whether statObjectSignature passes",
                TestStatus.FAIL, DateTime.Now - startTime, ex.Message, ex.ToString(), args: args).Log();
            throw;
        }
        finally
        {
            await TearDown(minio, bucketName);
        }
    }
```

**Comment by harshavardhana** [comment]
If you don't know what you are doing, I can send comprehensive change properly.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
